#!/bin/bash
#============================================================================================================================
# example         : sh script.sh pm1 pm2 pm3 pm4 pm5 pm6 pm7 pm8
#
#============================================================================================================================


#============================================================================================================================
#function to check error at any stage
#============================================================================================================================
function errorHandler
{

  if [ $# -lt 2 ]
  then
          writeLog "ERROR" "USAGE: errorHandler <retrurn_code> <error_msg> <success_msg>"
  fi

  returnValue=$1
  errorValue=$2
  successValue=$3
  
  if [ $# -eq 2 ]
  then
          if [ ${returnValue} -ne 0 ]
          then
                  writeLog "ERROR" "${errorValue} Exiting with value ${returnValue}!!!"
                  exit ${returnValue}
          fi
  fi
  
  if [ $# -eq 3 ]
  then
          if [ ${returnValue} -ne 0 ]
          then
                  writeLog "ERROR" "${errorValue} Exiting with value ${returnValue}!!!"
                  exit ${returnValue}
  		else
  				writeLog "SUCCESS" "${successValue} Exiting with value ${returnValue}!!!"
          fi
  fi

}


#============================================================================================================================
#function to write log into log file
#============================================================================================================================
function writeLog
{
  type=$1
  msg=$2
  timestamp=`date '+%Y-%m-%d %H:%M:%S'`
  
  echo "${timestamp}:[${type}]:${msg}" >> ${log_file}
}


#============================================================================================================================
#function to check log file at the end of the JOB
#============================================================================================================================
function check_logfile
{
  if [[ `cat ${log_file}  | grep -vE "INFO|WARN" | grep -icE "error|exception|semantic" ` -gt 0 ]]
  then
      process_status='failed'       
      insert_status
      writeLog "Error in ${process} HQL execution, please check the logs: ${log_file}" 
      exit 1
  else
      process_status='success'
      writeLog "${process} HQL execution successful.. "
  fi
}


#MAIN
#============================================================================================================================
#check passed input parameters 
#============================================================================================================================
if [ $# -ne 8 ]
then
        errorHandler 1 "Script Usage: retention.sh <pm1> <pm2> <pm3> <pm4> <pm5> <pm6> <pm7> <pm8>"
        writeLog 1 "passed parameters <pm1> $1 <pm2> $2 <pm3> $3 <pm4> $4 <pm5> $5 <pm6> $6 <pm7> $7 <pm8> $8"
fi


#============================================================================================================================
#Assigning INPUT parameteres 
#============================================================================================================================
cty=$1
system=$2
source_db=$3
target_db=$4
env=$5
start_date=$6
end_date=$7
p_thread=$8

system_name=`echo ${system} | tr '[:upper:]' '[:lower:]'`
country=`echo ${cty} | tr '[:lower:]' '[:upper:]'`
ods=$ods_start_date

DATE=`date +%Y-%m-%d`
STAMP=$(date +'%Y-%m-%d %H:%M:%S')
ods_start_date=`date --date "${start_date}-1 days" +'%Y%m%d'`
ods_end_date=`date --date "${end_date}-1 days" +'%Y%m%d'`
ods=`date +"%Y-%m-%d" -d ${ods_start_date}`
startDate=`date +"%Y-%m-%d" -d ${ods_start_date}`
endDate=`date +"%Y-%m-%d" -d ${ods_end_date}`


#============================================================================================================================
#enable files with parameters
#============================================================================================================================
. ${data}/Scripts/connection.conf
BEELINE_CONN=$(eval echo \$CONNECTION_${Env})


#============================================================================================================================
#Files declaration
#============================================================================================================================
log_path=<home_path>/${system}/logs
log_file=$log_path/${system_name}${env}_${cty}_DataCopy_${DATE}.log
table_list=<$home_path>/${system}/hql/${country}/${system_name}_${env}_TablesList.txt
column_list=<$home_path>/${system}/hql/${country}/${system_name}_${env}_ListColumns.hql
column_result=<$home_path>/${system}/hql/${system_name}_${env}_ListColumnsResult.txt
system_path=<$home_path>${system}
hql_dir=<$home_path>/${system}/hql/${country}/temp
path=<$home_path>/${system}/hql/${country}


>${log_file}
writeLog "==============================================================================" 
writeLog "$(date +'%Y-%m-%d %H:%M:%S') - " "Data Copy started"


#Fetching table list
writeLog " " " " 
writeLog "==============================================================================" 
writeLog "Table List " "Fetching the list of the tables from target db"
query="show tables in $target_db like '${table_type}*'"
${BEELINE_CONN} --showHeader=false --outputformat=tsv2 -e "${query}" > ${table_list}

hiveStatus=$?

errorHandler ${hiveStatus} "There is an issue while fetching the list of table from target schema" "Table list Fetched successfully" 
sed -i '/bridge/d' ${table_list}


#============================================================================================================================
#Prepare query for fetching columns
#============================================================================================================================
> ${column_list}
while IFS='' read -r line || [[ -n "$line" ]]; do
	echo "select * from ${target_db}.$line limit 0;" >> ${column_list}
done < ${table_list}

#Fetching table list
writeLog " " " "
writeLog "==============================================================================" 
writeLog "Columns " "Fetching the columns from table"

${BEELINE_CONN} --outputformat=tsv2 -f ${column_list} > ${column_result}

hiveStatus=$?

errorHandler ${hiveStatus} "There is an issue while fetching columns for table from target schema" "Columns for tables Fetched successfully"

sed -i '$d' ${column_result}
sed -i 's/[\t]/,/g' ${column_result}

parameters="set hive.execution.engine=tez;set hive.exec.parallel=true;set hive.cbo.enable=true;set hive.compute.query.using.stats=true;set hive.stats.fetch.column.stats=true;set hive.stats.fetch.partition.stats=true;set hive.tez.container.size=10240;set hive.tez.java.opts=-Xmx8192m;set tez.runtime.io.sort.mb=4096;set tez.runtime.unordered.output.buffer.size-mb=1024;set hive.auto.convert.join.noconditionaltask.size=100000000; set hive.auto.convert.join=false;set hive.vectorized.execution.enabled=false;set hive.vectorized.execution.reduce.enabled=false;SET hive.optimize.ppd=true;set hive.merge.mapfiles=true;set hive.merge.mapredfiles=true;set hive.merge.smallfiles.avgsize=104857600;set hive.merge.size.per.task=104857600;"


writeLog " " " "
writeLog "==============================================================================" 
writeLog "Query Files preparation" "Preparing queries to fetch data from source"


#============================================================================================================================
#Preparing query for execution
#============================================================================================================================
while IFS='' read -r line || [[ -n "$line" ]]; do
 
	#echo $line > $CAL_HOME_PK/Temp/test.txt
	tableName=`echo $line | cut -d. -f1`
	
	query="insert overwrite table ${target_db}.${tableName} partition(ods) select ${line} from ${source_db}.${tableName} where ods='${ods}';"
	
	echo ${parameters} > ${hql_dir}/${tableName}_${ods_start_date}.hql		
	echo $query >> ${hql_dir}/${tableName}_${ods_start_date}.hql
	
	sed -i "s/${tableName}.ods/regexp_replace(${tableName}.ods, '-', '_')/g" ${hql_dir}/${tableName}_${ods_start_date}.hql

done < ${column_result}


count=0
submitted=0
cat ${hql_dir}/* >> ${path}/${table_type}${env}_${ods_start_date}.hql

writeLog " " " "
writeLog "==============================================================================" 
writeLog "Query Execution " "Parallel Execution of Queries started"


#============================================================================================================================
#running query files in parallel
#============================================================================================================================
while IFS='' read -r line || [[ -n "${line}" ]]; do
        file_hql=${line}_${ods_start_date}.hql
        
        echo "nohup ${system_path}/${system_name}_pk_dataload.sh $file_hql $hql_dir ${country} ${log_file} ${log_file}" >> $log_file
		
		nohup ${system_path}/${system_name}_pk_dataload.sh ${file_hql} ${hql_dir} ${country} ${log_file} ${log_file} > /dev/null 2>&1&
        
		count=$((count+1))
		submitted=$((submitted+1))

		sleep 5
		if [ ${count} -ge ${p_thread} ]; then
			
			processes=`ps -ef | grep ${system_path}/${system_name}_pk_dataload.sh | wc -l`
			
			while [ $processes -gt 5 ]
			do
				processes=`ps -ef | grep ${system_path}/${system_name}_pk_dataload.sh | wc -l`
				
				sleep 10
			done
                count=${processes}
		fi
done < ${table_list}

script_end=2 
while [ $script_end -ge 2 ] 
do 
        sleep 30 
        script_end=`ps -ef | grep ${system_path}/${system_name}_pk_dataload.sh | wc -l` 
done


type=country_filter
process=country_filter
check_logfile
rm -rf ${path}/cnty/*_${ods_start_date}.hql

echo "ods_start_date=${ods_start_date} & ods_end_date=${ods_end_date}" >> $log_file
echo "country filter script execution for ${system} ${country} ended at `date`" >> $log_file
echo "country filter ended for ${system} ${country} at `date`"


#!/bin/bash
#============================================================================================================================
# Script Name     : supporting script to actuaaly submitting the JOB
#============================================================================================================================
#================================================== ASINGING PARAMETERS =====================================================
#============================================================================================================================
file_hql=$1
path_hql=$2
cty=$3
log_file=$4
hql_exec_log_file=$5

. ${CAL_HOME_PK}/Scripts/connection.conf

BEELINE_CONN=$(eval echo \$CONNECTION_$Env)

echo "$file_hql is started.." >> $log_file
date >> $log_file

#BEELINE_CHANGES
${BEELINE_CONN} --silent=true -f $path_hql/$file_hql 2>> $hql_exec_log_file

hive_status=$?

	if [ $hive_status -ne 0 ]; then
		echo "ERROR: $file_hql - HQL failed" >> ${log_file}
		exit 1
	else 
		echo "$file_hql - Finished successfully" >> ${log_file}
	fi
	
echo "$file_hql is Ended.." >> ${log_file}
date >> $log_file

